//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tovar.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderedProducts = new HashSet<OrderedProducts>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int MeasureUnitId { get; set; }
        public double Price { get; set; }
        public double MaxDiscountSize { get; set; }
        public int ManufacturerId { get; set; }
        public int SupplierId { get; set; }
        public int ProductCategoryId { get; set; }
        public double CurrentDiscount { get; set; }
        public int QuantityInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MeasureUnits MeasureUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedProducts> OrderedProducts { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
